### ISSUE TITLE
Fixes NPE when rewriting column without column index

### ISSUE THREAD

**Issue by rok** [rok/test-parquet-java#1436]
The ColumnIndex could be null in some scenes, for example, the float/double column contains NaN or the size has exceeded the expected value. And the page header statistics are not written anymore after we supported ColumnIndex. So we will get NPE when rewriting the column without ColumnIndex due to we need to get NULL page statistics when converted from the ColumnIndex(NULL) or page header statistics(NULL). Such as the following:
```java
java.lang.NullPointerException
	at org.apache.parquet.hadoop.ParquetFileWriter.writeDataPage(ParquetFileWriter.java:727)
	at org.apache.parquet.hadoop.ParquetFileWriter.innerWriteDataPage(ParquetFileWriter.java:663)
	at org.apache.parquet.hadoop.ParquetFileWriter.writeDataPage(ParquetFileWriter.java:650)
	at org.apache.parquet.hadoop.rewrite.ParquetRewriter.processChunk(ParquetRewriter.java:453)
	at org.apache.parquet.hadoop.rewrite.ParquetRewriter.processBlocksFromReader(ParquetRewriter.java:317)
	at org.apache.parquet.hadoop.rewrite.ParquetRewriter.processBlocks(ParquetRewriter.java:250)

```

**Reporter**: [Xianyang Liu](https://issues.apache.org/jira/secure/ViewProfile.jspa?name=coneyliu) / @ConeyLiu

<sub>**Note**: *This issue was originally created as [PARQUET-2365](https://issues.apache.org/jira/browse/PARQUET-2365). Please see the [migration documentation](https://github.com/apache/arrow/issues/14542) for further details.*</sub>

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17776098):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17776109):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17776118):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17776990):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17777618):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17779550):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17780367):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17780368):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17780370):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17782431):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17782433):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17782440):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17782475):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17782491):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17782494):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17782497):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17782499):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17782561):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17782562):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17782563):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17782644):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17782651):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17782852):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17782874):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17784666):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17784668):

**Comment by rok** [comment]
[ASF GitHub Bot](https://issues.apache.org/jira/browse/PARQUET-2365?#comment-17784670):
